"""Application-wide constants for solver and constraint defaults."""

SOLVER_TIMEOUT_MS: int = 300_000
MAX_SOLVER_VARIABLES: int = 50_000
SOLVER_RANDOM_SEED: int = 42
SOLVER_STALE_JOB_BUFFER_SECONDS: int = 60
SOLVER_PROCESS_MEMORY_LIMIT_MB: int = 2_048
EPSILON: float = 0.001

MAX_HOURS_PER_WEEK_DEFAULT: int = 40
MAX_HOURS_PER_WEEK_PENALTY: float = -50.0

CONSECUTIVE_REST_HOURS_DEFAULT: int = 12
CONSECUTIVE_REST_PENALTY: float = -30.0

WORKER_PREFERENCE_REWARD: int = 10
WORKER_PREFERENCE_PENALTY: int = -100

TASK_PRIORITY_BASE_PENALTY: float = -20.0
MUTUAL_EXCLUSION_PENALTY: float = -100.0
CO_LOCATION_PENALTY: float = -50.0
